name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: tar czvf target/release/brightness.tar.gz target/release/brightness
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/brightness.tar.gz
          asset_name: brightness-linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
